export const CRIME_STATUSES = {
  RECRUITING: "Recruiting",
  PLANNING: "Planning",
  ONGOING: "Ongoing",
  SUCCESSFUL: "Successful",
  FAILED: "Failed",
  EXPIRED: "Expired",
} as const

export type CrimeStatus = typeof CRIME_STATUSES[keyof typeof CRIME_STATUSES]

export const STATUS_ORDER = [
  CRIME_STATUSES.RECRUITING,
  CRIME_STATUSES.PLANNING,
  CRIME_STATUSES.ONGOING,
  CRIME_STATUSES.SUCCESSFUL,
  CRIME_STATUSES.FAILED,
  CRIME_STATUSES.EXPIRED,
]

export const ACTIVE_STATUSES = [
  CRIME_STATUSES.RECRUITING,
  CRIME_STATUSES.PLANNING,
  CRIME_STATUSES.ONGOING,
]

export const COMPLETED_STATUSES = [
  CRIME_STATUSES.SUCCESSFUL,
  CRIME_STATUSES.FAILED,
  CRIME_STATUSES.EXPIRED,
]
